services:
  next-app:
    container_name: live-sql-prod
    image: live-sql-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./opt/oracle/instantclient_19_12:/opt/oracle/instantclient_19_12
    restart: always
    ports:
      - 3001:3001
